import type { KeyedTokensInfo } from "shiki-magic-move/types";

export const steps = [
  {
    code: 'import { useOpenWalletModal } from "@0xsequence/kit-wallet";\nimport { useOpenConnectModal } from "@0xsequence/kit";\nimport { useAccount } from "wagmi";\nexport const WalletInventoryWidget = () => {\n  const { address } = useAccount();\n  const { setOpenConnectModal } = useOpenConnectModal();\n  const { setOpenWalletModal } = useOpenWalletModal();\n  return address ? (\n    <>\n      <p>Connected as {address}</p>\n      <button onClick={() => setOpenWalletModal(true)}>\n        Open Wallet Inventory\n      </button>\n    </>\n  ) : (\n    <>\n      <p>Not connected</p>\n      <button onClick={() => setOpenConnectModal(true)}>Connect</button>\n    </>\n  );\n};',
    hash: "wS0U7Qwxr9",
    tokens: [
      {
        key: "wS0U7Qwxr9-ln-1",
        content: " 1  ",
        offset: 0,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "import",
        offset: 0,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-1",
      },
      {
        content: " ",
        offset: 6,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-2",
      },
      {
        content: "{",
        offset: 7,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-3",
      },
      {
        content: " ",
        offset: 8,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-4",
      },
      {
        content: "useOpenWalletModal",
        offset: 9,
        color: "#FFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-5",
      },
      {
        content: " ",
        offset: 27,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-6",
      },
      {
        content: "}",
        offset: 28,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-7",
      },
      {
        content: " ",
        offset: 29,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-8",
      },
      {
        content: "from",
        offset: 30,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-9",
      },
      {
        content: " ",
        offset: 34,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-10",
      },
      {
        content: '"',
        offset: 35,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-11",
      },
      {
        content: "@0xsequence/kit-wallet",
        offset: 36,
        color: "#B4DCE7",
        fontStyle: 0,
        key: "wS0U7Qwxr9-12",
      },
      {
        content: '"',
        offset: 58,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-13",
      },
      {
        content: ";",
        offset: 59,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-14",
      },
      { content: "\n", offset: 60, key: "wS0U7Qwxr9-15" },
      {
        key: "wS0U7Qwxr9-ln-2",
        content: " 2  ",
        offset: 61,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "import",
        offset: 61,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-17",
      },
      {
        content: " ",
        offset: 67,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-18",
      },
      {
        content: "{",
        offset: 68,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-19",
      },
      {
        content: " ",
        offset: 69,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-20",
      },
      {
        content: "useOpenConnectModal",
        offset: 70,
        color: "#FFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-21",
      },
      {
        content: " ",
        offset: 89,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-22",
      },
      {
        content: "}",
        offset: 90,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-23",
      },
      {
        content: " ",
        offset: 91,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-24",
      },
      {
        content: "from",
        offset: 92,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-25",
      },
      {
        content: " ",
        offset: 96,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-26",
      },
      {
        content: '"',
        offset: 97,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-27",
      },
      {
        content: "@0xsequence/kit",
        offset: 98,
        color: "#B4DCE7",
        fontStyle: 0,
        key: "wS0U7Qwxr9-28",
      },
      {
        content: '"',
        offset: 113,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-29",
      },
      {
        content: ";",
        offset: 114,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-30",
      },
      { content: "\n", offset: 115, key: "wS0U7Qwxr9-31" },
      {
        key: "wS0U7Qwxr9-ln-3",
        content: " 3  ",
        offset: 116,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "import",
        offset: 116,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-33",
      },
      {
        content: " ",
        offset: 122,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-34",
      },
      {
        content: "{",
        offset: 123,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-35",
      },
      {
        content: " ",
        offset: 124,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-36",
      },
      {
        content: "useAccount",
        offset: 125,
        color: "#FFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-37",
      },
      {
        content: " ",
        offset: 135,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-38",
      },
      {
        content: "}",
        offset: 136,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-39",
      },
      {
        content: " ",
        offset: 137,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-40",
      },
      {
        content: "from",
        offset: 138,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-41",
      },
      {
        content: " ",
        offset: 142,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-42",
      },
      {
        content: '"',
        offset: 143,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-43",
      },
      {
        content: "wagmi",
        offset: 144,
        color: "#B4DCE7",
        fontStyle: 0,
        key: "wS0U7Qwxr9-44",
      },
      {
        content: '"',
        offset: 149,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-45",
      },
      {
        content: ";",
        offset: 150,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-46",
      },
      { content: "\n", offset: 151, key: "wS0U7Qwxr9-47" },
      {
        key: "wS0U7Qwxr9-ln-4",
        content: " 4  ",
        offset: 152,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "export",
        offset: 152,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-49",
      },
      {
        content: " ",
        offset: 158,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-50",
      },
      {
        content: "const",
        offset: 159,
        color: "#A96BC0",
        fontStyle: 0,
        key: "wS0U7Qwxr9-51",
      },
      {
        content: " ",
        offset: 164,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-52",
      },
      {
        content: "WalletInventoryWidget",
        offset: 165,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-53",
      },
      {
        content: " ",
        offset: 186,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-54",
      },
      {
        content: "=",
        offset: 187,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-55",
      },
      {
        content: " ",
        offset: 188,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-56",
      },
      {
        content: "()",
        offset: 189,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-57",
      },
      {
        content: " ",
        offset: 191,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-58",
      },
      {
        content: "=>",
        offset: 192,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-59",
      },
      {
        content: " ",
        offset: 194,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-60",
      },
      {
        content: "{",
        offset: 195,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-61",
      },
      { content: "\n", offset: 196, key: "wS0U7Qwxr9-62" },
      {
        key: "wS0U7Qwxr9-ln-5",
        content: " 5  ",
        offset: 197,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 197,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-64",
      },
      {
        content: "const",
        offset: 199,
        color: "#A96BC0",
        fontStyle: 0,
        key: "wS0U7Qwxr9-65",
      },
      {
        content: " ",
        offset: 204,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-66",
      },
      {
        content: "{",
        offset: 205,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-67",
      },
      {
        content: " ",
        offset: 206,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-68",
      },
      {
        content: "address",
        offset: 207,
        color: "#FFE261",
        fontStyle: 0,
        key: "wS0U7Qwxr9-69",
      },
      {
        content: " ",
        offset: 214,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-70",
      },
      {
        content: "}",
        offset: 215,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-71",
      },
      {
        content: " ",
        offset: 216,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-72",
      },
      {
        content: "=",
        offset: 217,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-73",
      },
      {
        content: " ",
        offset: 218,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-74",
      },
      {
        content: "useAccount",
        offset: 219,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-75",
      },
      {
        content: "();",
        offset: 229,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-76",
      },
      { content: "\n", offset: 232, key: "wS0U7Qwxr9-77" },
      {
        key: "wS0U7Qwxr9-ln-6",
        content: " 6  ",
        offset: 233,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 233,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-79",
      },
      {
        content: "const",
        offset: 235,
        color: "#A96BC0",
        fontStyle: 0,
        key: "wS0U7Qwxr9-80",
      },
      {
        content: " ",
        offset: 240,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-81",
      },
      {
        content: "{",
        offset: 241,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-82",
      },
      {
        content: " ",
        offset: 242,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-83",
      },
      {
        content: "setOpenConnectModal",
        offset: 243,
        color: "#FFE261",
        fontStyle: 0,
        key: "wS0U7Qwxr9-84",
      },
      {
        content: " ",
        offset: 262,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-85",
      },
      {
        content: "}",
        offset: 263,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-86",
      },
      {
        content: " ",
        offset: 264,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-87",
      },
      {
        content: "=",
        offset: 265,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-88",
      },
      {
        content: " ",
        offset: 266,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-89",
      },
      {
        content: "useOpenConnectModal",
        offset: 267,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-90",
      },
      {
        content: "();",
        offset: 286,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-91",
      },
      { content: "\n", offset: 289, key: "wS0U7Qwxr9-92" },
      {
        key: "wS0U7Qwxr9-ln-7",
        content: " 7  ",
        offset: 290,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 290,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-94",
      },
      {
        content: "const",
        offset: 292,
        color: "#A96BC0",
        fontStyle: 0,
        key: "wS0U7Qwxr9-95",
      },
      {
        content: " ",
        offset: 297,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-96",
      },
      {
        content: "{",
        offset: 298,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-97",
      },
      {
        content: " ",
        offset: 299,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-98",
      },
      {
        content: "setOpenWalletModal",
        offset: 300,
        color: "#FFE261",
        fontStyle: 0,
        key: "wS0U7Qwxr9-99",
      },
      {
        content: " ",
        offset: 318,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-100",
      },
      {
        content: "}",
        offset: 319,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-101",
      },
      {
        content: " ",
        offset: 320,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-102",
      },
      {
        content: "=",
        offset: 321,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-103",
      },
      {
        content: " ",
        offset: 322,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-104",
      },
      {
        content: "useOpenWalletModal",
        offset: 323,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-105",
      },
      {
        content: "();",
        offset: 341,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-106",
      },
      { content: "\n", offset: 344, key: "wS0U7Qwxr9-107" },
      {
        key: "wS0U7Qwxr9-ln-8",
        content: " 8  ",
        offset: 345,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 345,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-109",
      },
      {
        content: "return",
        offset: 347,
        color: "#40B4C4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-110",
      },
      {
        content: " ",
        offset: 353,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-111",
      },
      {
        content: "address",
        offset: 354,
        color: "#FFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-112",
      },
      {
        content: " ",
        offset: 361,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-113",
      },
      {
        content: "?",
        offset: 362,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-114",
      },
      {
        content: " ",
        offset: 363,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-115",
      },
      {
        content: "(",
        offset: 364,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-116",
      },
      { content: "\n", offset: 365, key: "wS0U7Qwxr9-117" },
      {
        key: "wS0U7Qwxr9-ln-9",
        content: " 9  ",
        offset: 366,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "    ",
        offset: 366,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-119",
      },
      {
        content: "<>",
        offset: 370,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-120",
      },
      { content: "\n", offset: 372, key: "wS0U7Qwxr9-121" },
      {
        key: "wS0U7Qwxr9-ln-10",
        content: "10  ",
        offset: 373,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "      ",
        offset: 373,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-123",
      },
      {
        content: "<",
        offset: 379,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-124",
      },
      {
        content: "p",
        offset: 380,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-125",
      },
      {
        content: ">",
        offset: 381,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-126",
      },
      {
        content: "Connected as",
        offset: 382,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-127",
      },
      { content: " ", offset: 394, key: "wS0U7Qwxr9-128" },
      {
        content: "{",
        offset: 395,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-129",
      },
      {
        content: "address",
        offset: 396,
        color: "#FFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-130",
      },
      {
        content: "}</",
        offset: 403,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-131",
      },
      {
        content: "p",
        offset: 406,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-132",
      },
      {
        content: ">",
        offset: 407,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-133",
      },
      { content: "\n", offset: 408, key: "wS0U7Qwxr9-134" },
      {
        key: "wS0U7Qwxr9-ln-11",
        content: "11  ",
        offset: 409,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "      ",
        offset: 409,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-136",
      },
      {
        content: "<",
        offset: 415,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-137",
      },
      {
        content: "button",
        offset: 416,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-138",
      },
      {
        content: " ",
        offset: 422,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-139",
      },
      {
        content: "onClick",
        offset: 423,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-140",
      },
      {
        content: "=",
        offset: 430,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-141",
      },
      {
        content: "{()",
        offset: 431,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-142",
      },
      {
        content: " ",
        offset: 434,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-143",
      },
      {
        content: "=>",
        offset: 435,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-144",
      },
      {
        content: " ",
        offset: 437,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-145",
      },
      {
        content: "setOpenWalletModal",
        offset: 438,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-146",
      },
      {
        content: "(",
        offset: 456,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-147",
      },
      {
        content: "true",
        offset: 457,
        color: "#FFE261",
        fontStyle: 0,
        key: "wS0U7Qwxr9-148",
      },
      {
        content: ")}>",
        offset: 461,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-149",
      },
      { content: "\n", offset: 464, key: "wS0U7Qwxr9-150" },
      {
        key: "wS0U7Qwxr9-ln-12",
        content: "12  ",
        offset: 465,
        htmlClass: "shiki-magic-move-line-number",
      },
      { content: "        ", offset: 465, key: "wS0U7Qwxr9-152" },
      {
        content: "Open Wallet Inventory",
        offset: 473,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-153",
      },
      { content: "\n", offset: 494, key: "wS0U7Qwxr9-154" },
      {
        key: "wS0U7Qwxr9-ln-13",
        content: "13  ",
        offset: 495,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "      ",
        offset: 495,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-156",
      },
      {
        content: "</",
        offset: 501,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-157",
      },
      {
        content: "button",
        offset: 503,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-158",
      },
      {
        content: ">",
        offset: 509,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-159",
      },
      { content: "\n", offset: 510, key: "wS0U7Qwxr9-160" },
      {
        key: "wS0U7Qwxr9-ln-14",
        content: "14  ",
        offset: 511,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "    ",
        offset: 511,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-162",
      },
      {
        content: "</>",
        offset: 515,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-163",
      },
      { content: "\n", offset: 518, key: "wS0U7Qwxr9-164" },
      {
        key: "wS0U7Qwxr9-ln-15",
        content: "15  ",
        offset: 519,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 519,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-166",
      },
      {
        content: ")",
        offset: 521,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-167",
      },
      {
        content: " ",
        offset: 522,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-168",
      },
      {
        content: ":",
        offset: 523,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-169",
      },
      {
        content: " ",
        offset: 524,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-170",
      },
      {
        content: "(",
        offset: 525,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-171",
      },
      { content: "\n", offset: 526, key: "wS0U7Qwxr9-172" },
      {
        key: "wS0U7Qwxr9-ln-16",
        content: "16  ",
        offset: 527,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "    ",
        offset: 527,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-174",
      },
      {
        content: "<>",
        offset: 531,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-175",
      },
      { content: "\n", offset: 533, key: "wS0U7Qwxr9-176" },
      {
        key: "wS0U7Qwxr9-ln-17",
        content: "17  ",
        offset: 534,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "      ",
        offset: 534,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-178",
      },
      {
        content: "<",
        offset: 540,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-179",
      },
      {
        content: "p",
        offset: 541,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-180",
      },
      {
        content: ">",
        offset: 542,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-181",
      },
      {
        content: "Not connected",
        offset: 543,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-182",
      },
      {
        content: "</",
        offset: 556,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-183",
      },
      {
        content: "p",
        offset: 558,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-184",
      },
      {
        content: ">",
        offset: 559,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-185",
      },
      { content: "\n", offset: 560, key: "wS0U7Qwxr9-186" },
      {
        key: "wS0U7Qwxr9-ln-18",
        content: "18  ",
        offset: 561,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "      ",
        offset: 561,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-188",
      },
      {
        content: "<",
        offset: 567,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-189",
      },
      {
        content: "button",
        offset: 568,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-190",
      },
      {
        content: " ",
        offset: 574,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-191",
      },
      {
        content: "onClick",
        offset: 575,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-192",
      },
      {
        content: "=",
        offset: 582,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-193",
      },
      {
        content: "{()",
        offset: 583,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-194",
      },
      {
        content: " ",
        offset: 586,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-195",
      },
      {
        content: "=>",
        offset: 587,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-196",
      },
      {
        content: " ",
        offset: 589,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-197",
      },
      {
        content: "setOpenConnectModal",
        offset: 590,
        color: "#EB64B9",
        fontStyle: 0,
        key: "wS0U7Qwxr9-198",
      },
      {
        content: "(",
        offset: 609,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-199",
      },
      {
        content: "true",
        offset: 610,
        color: "#FFE261",
        fontStyle: 0,
        key: "wS0U7Qwxr9-200",
      },
      {
        content: ")}>",
        offset: 614,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-201",
      },
      {
        content: "Connect",
        offset: 617,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-202",
      },
      {
        content: "</",
        offset: 624,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-203",
      },
      {
        content: "button",
        offset: 626,
        color: "#74DFC4",
        fontStyle: 0,
        key: "wS0U7Qwxr9-204",
      },
      {
        content: ">",
        offset: 632,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-205",
      },
      { content: "\n", offset: 633, key: "wS0U7Qwxr9-206" },
      {
        key: "wS0U7Qwxr9-ln-19",
        content: "19  ",
        offset: 634,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "    ",
        offset: 634,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-208",
      },
      {
        content: "</>",
        offset: 638,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-209",
      },
      { content: "\n", offset: 641, key: "wS0U7Qwxr9-210" },
      {
        key: "wS0U7Qwxr9-ln-20",
        content: "20  ",
        offset: 642,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "  ",
        offset: 642,
        color: "#FFFFFF",
        fontStyle: 0,
        key: "wS0U7Qwxr9-212",
      },
      {
        content: ");",
        offset: 644,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-213",
      },
      { content: "\n", offset: 646, key: "wS0U7Qwxr9-214" },
      {
        key: "wS0U7Qwxr9-ln-21",
        content: "21  ",
        offset: 647,
        htmlClass: "shiki-magic-move-line-number",
      },
      {
        content: "};",
        offset: 647,
        color: "#7B6995",
        fontStyle: 0,
        key: "wS0U7Qwxr9-216",
      },
      { content: "\n", offset: 649, key: "wS0U7Qwxr9-217" },
    ],
    lineNumbers: false,
    bg: "#27212e",
    fg: "#ffffff",
    themeName: "laserwave",
    lang: "jsx",
  },
] as KeyedTokensInfo[];
