// This file is generated by npm run build:icons

export type IconName =
	| "arrow-left"
	| "book-base"
	| "book-cover-coins"
	| "book-cover-connection"
	| "book-cover-globe"
	| "book-cover-inventory"
	| "book-cover-list"
	| "book-cover-marketplace"
	| "book-cover-minter"
	| "book-cover-payments"
	| "book-cover-wallet"
	| "copy"
	| "monetize"
	| "onboard"
	| "power"
